### PR TITLE
Master port to OM - ITSMChangeManagement

### PR DESCRIPTION
**Pull request by s7design**
Hello @UdoBretz ,

Here is last port for ITSM modules. As you probably expected, this is the biggest one and therefore affected most files. If it's inconvenient for you to check whole module at once, I could split it in couple of PRs. Although I am not certain at what length they are connected, so it would be difficult to have partial  working ports in different PRs. Please correct me here if I am wrong and you know how could split be done for easier review.

I tested manually each module, while porting, and gonna start writing selenium tests now. This will allow me to better understand ITSMChangeManagement and spot if any error arise, caused by port. Will notify you if there are any changes necessary further on.

ITSMChangeManagement command and selenium tests will be created soon in new PRs.

Regards,
Sanjin

### CODE REVIEW

**Comment by s7design** [comment]
Hi @UdoBretz 

While were doing on Selenium tests we saw that there is an issue with Notification for Change package.
It is expected because there has been some changes with Notification and NotificationEvent in OTRS recently. 

We will be able to solve this if somebody else don't already do on this. I suggest that we fix this in another PR after merging this one. 

Because of that and Selenium tests it would be nice if this PR was merged as soon as possible. I believe it is not good if  we add new commits on this PR. Of course it is so huge, and I understand that it is needed time for follow up. In any case we will be in touch and we will solve the best we can.

P.S. Martin's opinion is welcome here, of course.

Regards
Zoran

**Comment by mgruner** [comment]
Hi Zoran,
I believe that Udo plans to do the neccessary changes for the new
notification system, you probably don't need to take care of it.
Regards, mg

Am 30.06.15 um 11:52 schrieb S7 Design:
> Hi @UdoBretz <https://github.com/UdoBretz>
> 
> While were doing on Selenium tests we saw that there is an issue with
> Notification for Change package.
> It is expected because there has been some changes with Notification and
> NotificationEvent in OTRS recently.
> 
> We will be able to solve this if somebody else don't already do on this.
> I suggest that we fix this in another PR after merging this one.
> 
> Because of that and Selenium tests it would be nice if this PR was
> merged as soon as possible. I believe it is not good if we add new
> commits on this PR. Of course it is so huge, and I understand that it is
> needed time for follow up. In any case we will be in touch and we will
> solve the best we can.
> 
> P.S. Martin's opinion is welcome here, of course.
> 
> Regards
> Zoran
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/ITSMChangeManagement/pull/4#issuecomment-117102318>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Grenzenlose Kommunikation mit der OTRS Business Solution™! Bereichern
Sie Ihren IT Support und Kundenservice mit smarten Business Features!
https://www.otrs.com/solutions/otrs-business-solution-on-premise/?lang=de/#OTRS-Business-Solution-Basic-Features

**Comment by s7design** [comment]
Nice, thanks Martin.

Regards
Zoran

**Comment by UdoBretz** [comment]
Hi Zoran,

yes, there is some work in progress on my side for the channge notifications, so you could ignore this part for now. I will review and merge this pull request later today.

Thank you,
Udo

**Comment by UdoBretz** [comment]
Merged! Thank you!

**Pull request closed without merging**
